### ISSUE TITLE
Errors during compile/test (scala_2_8 branch)

### ISSUE THREAD

**Issue by andrewmilkowski** [rhavyn/norbert#2]
Hey Chris

Trying to test-bed this project, using scala 2.8.0 , received compilation errors (full stack below)
I tried to change start method to connect in broken references and fire up zookeeper separately before sbt test  but to no avail...
I think you mock zookeeper anyways (or that is the intent)

thanks much in advance!

bash-3.2$ sbt compile 
[info] Building project norbert 1.0-SNAPSHOT against Scala 2.8.0
[info]    using NorbertProject with sbt 0.7.4 and Scala 2.7.7
[info] 
[info] == Norbert Cluster / compile ==
[info]   Source analysis: 0 new/modified, 0 indirectly invalidated, 0 removed.
[info] Compiling main sources...
[info] Nothing to compile.
[info]   Post-analysis: 230 classes.
[info] == Norbert Cluster / compile ==
[info] 
[info] == Norbert Java Cluster / compile ==
[info]   Source analysis: 9 new/modified, 0 indirectly invalidated, 0 removed.
[info] Compiling main sources...
[error] /opt/local/src/norbert/git/java-cluster/src/main/scala/com/linkedin/norbert/javacompat/cluster/InMemoryClusterClient.scala:21: value start is not a member of com.linkedin.norbert.cluster.memory.InMemoryClusterClient
[error]   underlying.start
[error]              ^
[error] /opt/local/src/norbert/git/java-cluster/src/main/scala/com/linkedin/norbert/javacompat/cluster/ZooKeeperClusterClient.scala:21: value start is not a member of com.linkedin.norbert.cluster.ClusterClient
[error]   underlying.start
[error]              ^
[error] two errors found
[info] == Norbert Java Cluster / compile ==
[info] 
[info] == Norbert Network / compile ==
[info]   Source analysis: 32 new/modified, 0 indirectly invalidated, 0 removed.
[info] Compiling main sources...
[error] /opt/local/src/norbert/git/network/src/main/scala/com/linkedin/norbert/network/common/BaseNetworkClient.scala:39: value start is not a member of com.linkedin.norbert.cluster.ClusterClient
[error]       clusterClient.start
[error]                     ^
[error] /opt/local/src/norbert/git/network/src/main/scala/com/linkedin/norbert/network/server/NetworkServer.scala:82: value start is not a member of com.linkedin.norbert.cluster.ClusterClient
[error]     clusterClient.start
[error]                   ^
[error] two errors found
[info] == Norbert Network / compile ==
[error] Error running compile: Compilation failed
[error] Error running compile: Compilation failed
[info] 
[info] Total time: 21 s, completed Sep 7, 2010 7:08:30 PM
[info] 
[info] Total session time: 22 s, completed Sep 7, 2010 7:08:30 PM
[error] Error during build.

**Comment by rhavyn** [comment]
Hello,

It looks like you are using the scala_2.8 branch.  That is currently the head of development and you are correct, it does not compile.  The networking code is in the middle of a refactor.  You should  try the 0.5_scala_2.8 branch which is the current stable branch that runs against scala 2.8.  Let me know if that also gives you problems.

Thanks,
--Chris

**Comment by andrewmilkowski** [comment]
Hey Crhis

Thank you very much (I am using your project to learn scala network API's) I am also trying to push/convert to scala 2.8 where possible (ie twitter scala libraries) it also adds to the learning effort:) 

0.5_scala_2.8 passed all specs, there is one spec that appeared to be ignored:

[info]   o register messages with the MessageHandlerRegistry

info] == Norbert Network / com.linkedin.norbert.network.server.NetworkServerSpec ==
[info] NetworkServerSpec
[info] NetworkServer should
[info]   + throw a NetworkShutdownException if the network has been shutdown
[info]   + throw a NetworkServerNotBound exception if bind has not be called
[info]   o register messages with the MessageHandlerRegistry
[info]   + when bind is called
...

there appears to be a defect with specs 1.6.5

http://code.google.com/p/specs/issues/detail?id=155

and it might be related

forcing spec 1.6.6-SNAPSHOT in the sbt breaks zookeeper pom dependencies 

and could have other side effects that I am not aware off.

thanks much !

**Comment by rhavyn** [comment]
You should be ok even if that spec is ignored, we're running the 0.5_scala_2.8 branch in production here with no major issues.  The next version of Norbert (what is being developed in the scala_2.8 branch) will have much better tests in general.

Again, let me know if you run into any problems or need any help.

--Chris
